function generateReport(evalCommand, evalOutput) {
    const reportId = generateReportID();
    const generatedOn = new Date().toISOString();
    
    return `
# OPA Evaluation Report

## Report Information
- **Report ID:** ${reportId}
- **Generated On:** ${generatedOn}
- **Generated By:** Your Name / Your Organization
- **Version:** 1.0

---

## 1. Executive Summary
This section provides a brief overview of the evaluation results and their implications. 

- **Objective:** To evaluate the compliance of the specified resources against established policies.
- **Key Findings:** The evaluated resources are compliant with the specified policies.

---

## 2. Command Executed
**Command:**
\`\`\`bash
${evalCommand}
\`\`\`

---

## 3. Evaluation Output
**Output:**
\`\`\`json
${JSON.stringify(evalOutput, null, 2)}
\`\`\`

---

## 4. Analysis
### 4.1 Overview of Results
The evaluation results indicate the following insights:

- **Overall Compliance:** The evaluated resources are compliant with the specified policies.
- **Exceptions:** There were no exceptions found during the evaluation.

### 4.2 Risk Assessment
Evaluate the potential risks associated with the current configurations:

- **High Risk:** None identified.
- **Medium Risk:** N/A
- **Low Risk:** N/A

---

## 5. Recommendations
Based on the output and analysis, consider the following recommendations:

1. **Policy Review:** Regularly review and update policies to adapt to new compliance requirements.
2. **Monitoring:** Implement ongoing monitoring of the evaluated resources to ensure continued compliance.
3. **Training:** Conduct training sessions for users to ensure they understand the policies.

---

## 6. Additional Notes
- Consider setting up automated alerts for non-compliance incidents.
- Ensure that all stakeholders are informed of policy changes.

---

## 7. Appendices
### Appendix A: Command Details
- **Command Executed:** The specific command used for the evaluation.
- **Execution Time:** Time taken to execute the command.

### Appendix B: References
- [Open Policy Agent Documentation](https://www.openpolicyagent.org/docs/latest/)
- [Your Organization’s Policy Documentation](link_to_your_policy_documentation)

---

## 8. Audit Log
- **Log Entry 1:** Command executed on ${generatedOn} by User1.
- **Log Entry 2:** Evaluation completed successfully.
    `;
}
